name: CI

on:
  push:
    branches: [ master ]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun test
      - run: bun run build
      - run: bun publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}