name: CI

on:
  push:
    branches: [ master ]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
          registry-url: @brian-pob:https://registry.npmjs.org/
      - run: bun install
      - run: bun test
      - run: bun run build
      - run: bun publish --provenance --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}